FROM node:8.9.3-alpine

WORKDIR /app

ADD package.json /app
RUN set -uex; \
    npm install --production; \
    rm -rf /root/.npm;

ADD . /app

USER nobody
EXPOSE 8080
CMD ["/usr/bin/node", "/app/index.js"]

