FROM node:6.9.2

RUN set -uex; \
    npm install --no-cache -g forever; \
    ln -s /usr/local/bin/node /usr/bin/nodejs 

ADD package.json /
RUN npm install

WORKDIR /app
ADD . /app

EXPOSE 8080
CMD ["forever"]

