ARG NODE_VERSION="8.10.0"
FROM node:$NODE_VERSION

WORKDIR /app

ADD package.json /app
RUN set -uex; \
    npm install --production; \
    find /root; \
    npm cache clean --force;

ADD . /app

USER nobody
EXPOSE 8080
CMD ["/usr/local/bin/node", "/app/index.js"]
