FROM node:8.6

WORKDIR /app

ADD package.json /app
RUN set -uex; \
    npm install --production; \
    npm cache clean --force;

ADD . /app

USER nobody
EXPOSE 8080
CMD ["/usr/local/bin/node", "/app/index.js"]
