FROM node:8.9.1-alpine

# `forever` doesn't handle a `sigterm` or `sigint` properly when run in the foreground

# alpine has trouble recreating the cache dir after an `npm cache clean`, use `rm` instead
RUN set -uex; \
    npm install -g forever; \
    rm -rf /root/.npm;

WORKDIR /app

ADD package.json /app
RUN set -uex; \
    cd /app; \
    npm install -d; \
    rm -rf  /root/.npm;


ADD . /app

USER nobody
EXPOSE 8080
CMD ["forever", "/app/index.js"]
