FROM node:6.9.2

ARG DOCKER_BUILD_PROXY
ENV DOCKER_BUILD_PROXY $DOCKER_BUILD_PROXY

RUN ln -s /usr/local/bin/node /usr/bin/nodejs 

ADD package.json /
RUN npm install

WORKDIR /app
ADD . /app

EXPOSE 8080
CMD ["/usr/bin/nodejs", "/app/index.js"]

