ARG NODE_VERSION="8.10.0"

FROM node:$NODE_VERSION

# `forever` doesn't handle a `sigterm` or `sigint` properly when run in the foreground

RUN set -uex; \
    npm install -g forever; \
    npm cache clean --force;

WORKDIR /app

ADD package.json /app
RUN set -uex; \
    npm install; \
    npm cache clean --force;

ADD . /app

USER nobody
EXPOSE 8080
CMD ["forever", "/app/index.js"]
