FROM mhart/alpine-node:8.3.0

WORKDIR /app

ADD package.json /app
RUN set -uex; \
    npm install; \
    rm -rf /root/.npm;

ADD . /app

USER nobody
EXPOSE 8080
CMD ["/usr/bin/node", "/app/index.js"]

